### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by victorious85** [matthiasg/show-hide-windows-10-touchkeyboard#1]
Hi! I want to use your solution but could you help me to understand how to do that. How I could integrate you solution into my project?

**Comment by matthiasg** [comment]
Sorry for responding so late, I did not get an email that somebody wrote anything. Usage is documented in the README https://github.com/matthiasg/show-hide-windows-10-touchkeyboard#electron-usage and the Gist of it is to trigger show-keyboard or hide-keyboard exe from the main electron process triggered by a focusin etc event from the render processes. The render process sees an event, passes it via IPC to the main process which calls the appropriate show or hide.

I also made some improvements to the actual call handling which I will upload by the end of this week.

**Comment by matthiasg** [comment]
@victorious85 added some more info into the readme as to how to receive the events
