### ISSUE TITLE
Touch keyboard still doesnt popup 

### ISSUE THREAD

**Issue by musa-pro** [matthiasg/show-hide-windows-10-touchkeyboard#2]
Thanks @matthiasg to share your workaround codes. I was facing the same issue, thus I tried your codes, so I placed following files in root folder(where the package.json file is) -
```
show-touchkeyboard.exe 
hide-touchkeyboard.exe 
```
Then I called the following codes on field focus/blur
```
ipcRenderer.send('show-keyboard')
ipcRenderer.send('hide-keyboard')
```

But nothing happens. Btw, I can't change registry though as I don't(won't) have access. I also tried by placing all of your files. Do we need to write anything in main process file?
Now kind a lost, Appreciate your help.

Thanks

**Comment by matthiasg** [comment]
Did you add code to receive the events in you main script ?

Sending the `show-keyboard` or `hide-keyboard` events was only meant as an example to see how to forward the event to the main process which then calls the actual binaries.

Example:

```
const electron = require('electron')
const { spawn, execSync } = require('child_process')

...

  mainWindow.once('show', () => {
    electron.ipcMain.on('show-keyboard',() => {
      console.log('TRACE: showing keyboard ...')

      try {
        execSync('show-touchkeyboard.exe', { cwd: __dirname })
        console.log('started touch keyboard')
      } catch (error) {
        console.error('Error starting show touch keyboard', error)
      }
    })

    electron.ipcMain.on('hide-keyboard',() => {
      console.log('TRACE: hiding keyboard ...')

      try {
        execSync('hide-touchkeyboard.exe', { cwd: __dirname })
        console.log('hidden touch keyboard')
      } catch (error) {
        console.error('Error starting hide touch keyboard', error)
      }
    })
  })
```
